# Generated by Django 5.1.6 on 2025-02-21 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='joineddate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='phones',
            field=models.IntegerField(null=True),
        ),
    ]
